FROM oven/bun:1-alpine

WORKDIR /app

RUN apk add --no-cache git python3 make g++

RUN bun install -g onchange

COPY package.json bun.lock .

RUN bun install --verbose

COPY . .

EXPOSE 5173

CMD ["sh", "start-dev.sh"]
