services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
      - ../agent-worker/schema.json:/app/agent-worker/schema.json
    environment:
      AGENT_WORKER_DIR: agent-worker
    ports:
      - 5173:5173
