/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import * as z from 'zod'

// Base schemas for common properties
const baseMessageModel = z.object({
	id: z.string(),
	event: z.string(),
	// when you're on the same level (eg step_started and step_complete)
	sourceId: z.string().optional(),
	// the current run you're in
	runId: z.string(),
	// when you're nesting into a step
	stepId: z.string().optional()
})

export const userMessageModel = baseMessageModel.omit({ runId: true }).extend({
	event: z.literal('user_message'),
	data: z.object({
		content: z.array(
			z.object({
				type: z.literal('text'),
				text: z.string()
			})
		),
		context: z
			.record(
				z.string(),
				z.object({
					content: z.unknown()
				})
			)
			.default({})
	})
})

// Text message schemas
export const textMessageStartedModel = baseMessageModel.extend({
	event: z.literal('text_message_start'),
	data: z.object({})
})

export const textMessageContentModel = baseMessageModel.extend({
	event: z.literal('text_message_content'),
	sourceId: z.string().nonoptional(),
	data: z.object({
		delta: z.string()
	})
})

export const textMessageEndModel = baseMessageModel.extend({
	event: z.literal('text_message_end'),
	sourceId: z.string().nonoptional(),
	data: z.object({})
})

// Run schemas
export const runStartedModel = baseMessageModel.omit({ runId: true }).extend({
	event: z.literal('run_start'),
	data: z.object({})
})

export const runCompletedModel = baseMessageModel.omit({ runId: true }).extend({
	event: z.literal('run_complete'),
	sourceId: z.string().nonoptional(),
	data: z.object({})
})

// Step schemas
export const stepStartedModel = baseMessageModel.extend({
	event: z.literal('step_start'),
	runId: z.string().nonoptional(),
	data: z.object({
		title: z.string()
	})
})

export const stepCompletedModel = baseMessageModel.extend({
	event: z.literal('step_complete'),
	sourceId: z.string().nonoptional(),
	runId: z.string().nonoptional(),
	data: z.object({
		title: z.string()
	})
})

// Meta message schemas
export const ackMessageModel = baseMessageModel.omit({ id: true }).extend({
	event: z.literal('ack'),
	get data() {
		return uiMessageModel
	}
})

export const errorMessageModel = baseMessageModel.omit({ id: true }).extend({
	event: z.literal('error'),
	data: z.object({
		error: z.any() // Can contain validation errors or other error info
	})
})

const uiMessages = [
	userMessageModel,
	textMessageStartedModel,
	textMessageContentModel,
	textMessageEndModel,
	runStartedModel,
	runCompletedModel,
	stepStartedModel,
	stepCompletedModel
] as const

// Union of all message types
export const uiMessageModel = z.discriminatedUnion('event', uiMessages)
export const messageModel = z.discriminatedUnion('event', [
	...uiMessages,
	ackMessageModel,
	errorMessageModel
])

// same but without id
export const newMessageModel = z.discriminatedUnion('event', [
	userMessageModel.omit({ id: true }),
	textMessageStartedModel.omit({ id: true }),
	textMessageContentModel.omit({ id: true }),
	textMessageEndModel.omit({ id: true }),
	runStartedModel.omit({ id: true }),
	runCompletedModel.omit({ id: true }),
	stepStartedModel.omit({ id: true }),
	stepCompletedModel.omit({ id: true })
] as const)

// Array of messages
export const uiMessagesModel = z.array(uiMessageModel)
