/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import * as z from 'zod'

// Base schemas for common properties
const baseMessageModel = z.object({
	id: z.string(),
	event: z.string(),
	// when you're on the same level (eg step_started and step_complete)
	sourceId: z.string().optional(),
	// the current run you're in
	runId: z.string(),
	// when you're nesting into a step
	stepId: z.string().optional()
})

// const contextModel = z.discriminatedUnion('type', [
// 	z.object({
// 		type: z.literal('node').optional(),
// 		component_id: z.string().optional(),
// 		node_path: z.array(z.string()).optional(),
// 	}),
// 	// stuff like ~currentContainer, ~selectedNode etc
// 	z.object({
// 		type: z.literal('contextual').optional(),
// 		component_id: z.string()
// 	})
// ])

export const userMessageModel = baseMessageModel.omit({ runId: true }).extend({
	event: z.literal('user_message'),
	data: z.object({
		content: z.array(
			z.object({
				type: z.literal('text'),
				text: z.string()
			})
		),
		snapshot: z.string().optional(),
		context: z
			.record(
				z.string(),
				z.object({
					component_id: z.string().optional(),
					node_path: z.array(z.string()).optional(),
					container: z
						.object({
							type: z.enum(['component', 'project']),
							id: z.string()
						})
						.optional(),
					// backwards compatibility for now, remove later
					// no biggie that it's here for now
					content: z.unknown().optional()
				})
			)
			.default({})
	})
})

// Text message schemas
export const textMessageStartedModel = baseMessageModel.extend({
	event: z.literal('text_message_start'),
	data: z.object({})
})

export const textMessageContentModel = baseMessageModel.extend({
	event: z.literal('text_message_content'),
	sourceId: z.string().nonoptional(),
	data: z.object({
		delta: z.string()
	})
})

export const textMessageEndModel = baseMessageModel.extend({
	event: z.literal('text_message_end'),
	sourceId: z.string().nonoptional(),
	data: z.object({})
})

// Run schemas
export const runStartedModel = baseMessageModel.omit({ runId: true }).extend({
	event: z.literal('run_start'),
	data: z.object({})
})

const actionModels = z.discriminatedUnion('type', [
	z.object({
		type: z.literal('message_button'),
		message: z
			.string()
			.describe('the message to send when the button is clicked'),
		label: z.string().describe('the text on the button'),
		variation: z
			.enum([
				'primary',
				'vibrant',
				'link',
				'danger',
				'warning',
				'confirm',
				'ghost'
			])
			.default('primary')
			.describe('the variation of the button')
	}),
	z.object({
		type: z
			.literal('chat_project')
			.describe('deploys & opens the chat with the project selected')
	})
])

export const runCompletedModel = baseMessageModel.omit({ runId: true }).extend({
	event: z.literal('run_complete'),
	sourceId: z.string().nonoptional(),
	data: z.object({
		actions: z.array(actionModels).default([])
	})
})

// Step schemas
export const stepStartedModel = baseMessageModel.extend({
	event: z.literal('step_start'),
	runId: z.string().nonoptional(),
	data: z.object({
		title: z.string(),
		input: z.unknown().optional()
	})
})

export const stepCompletedModel = baseMessageModel.extend({
	event: z.literal('step_complete'),
	sourceId: z.string().nonoptional(),
	runId: z.string().nonoptional(),
	data: z.object({
		title: z.string(),
		status: z.enum(['success', 'error']).default('success'),
		output: z.unknown().optional()
	})
})

const widgetBaseModel = z.object({
	type: z.string().describe('the type of the widget'),
	props: z.object({}).describe('props that will be used in the frontend'),
	metadata: z
		.object({
			pendingComponents: z.array(
				z.object({
					componentId: z.string()
				})
			)
		})
		.describe('metadata mainly used by the builder to persist state')
})

const variableWidgetModel = widgetBaseModel.extend({
	type: z.literal('variable_prompt'),
	props: z.object({
		variables: z.array(
			z.object({
				key: z.string(),
				hint: z
					.object({
						text: z.string(),
						url: z.string()
					})
					.optional()
			})
		)
	})
})

const oauthWidgetModel = widgetBaseModel.extend({
	type: z.literal('oauth_prompt'),
	props: z.object({
		modifier_id: z
			.string()
			.describe('the id of the modifier pending authorisation')
	})
})

export const widgetsModel = z.discriminatedUnion('type', [
	variableWidgetModel,
	oauthWidgetModel
])

export const widgetStartedModel = baseMessageModel.extend({
	event: z.literal('widget_start'),
	data: widgetsModel
})
export const widgetCompletedModel = baseMessageModel
	.omit({ runId: true })
	.extend({
		event: z.literal('widget_complete'),
		sourceId: z.string().nonoptional(),
		data: z.object({})
	})

// Meta message schemas
export const ackMessageModel = baseMessageModel
	.omit({ id: true, runId: true })
	.extend({
		event: z.literal('ack'),
		get data() {
			return uiMessageModel
		}
	})

export const errorMessageModel = baseMessageModel
	.omit({ id: true, runId: true })
	.extend({
		event: z.literal('error'),
		data: z.object({
			error: z.any() // Can contain validation errors or other error info
		})
	})

export const pingMessageModel = baseMessageModel
	.omit({ id: true, runId: true })
	.extend({
		event: z.literal('ping'),
		data: z.object({}).default({})
	})

const uiMessages = [
	userMessageModel,
	textMessageStartedModel,
	textMessageContentModel,
	textMessageEndModel,
	runStartedModel,
	runCompletedModel,
	stepStartedModel,
	stepCompletedModel,
	widgetStartedModel,
	widgetCompletedModel
] as const

// Union of all message types
export const uiMessageModel = z.discriminatedUnion('event', uiMessages)
export const messageModel = z.discriminatedUnion('event', [
	...uiMessages,
	ackMessageModel,
	errorMessageModel,
	pingMessageModel
])

// same but without id
export const newMessageModel = z.discriminatedUnion('event', [
	userMessageModel.omit({ id: true }),
	textMessageStartedModel.omit({ id: true }),
	textMessageContentModel.omit({ id: true }),
	textMessageEndModel.omit({ id: true }),
	runStartedModel.omit({ id: true }),
	runCompletedModel.omit({ id: true }),
	stepStartedModel.omit({ id: true }),
	stepCompletedModel.omit({ id: true }),
	widgetStartedModel.omit({ id: true }),
	widgetCompletedModel.omit({ id: true })
] as const)

const cancelMessageModel = baseMessageModel
	.omit({ id: true, runId: true, stepId: true })
	.extend({
		event: z.literal('cancel'),
		data: z.object({}).default({})
	})

export const chatTriggerUserMessageModel = userMessageModel
	.omit({ id: true })
	.extend({
		data: userMessageModel.shape.data
			.omit({ context: true, snapshot: true })
			.extend({
				tools: z
					.array(
						z.object({
							projectId: z.string(),
							// support for selecting only a subset of the nodes, for now we just send them all
							// so there'll be n tools where n=nof top-level nodes in the project
							nodeId: z.string()
						})
					)
					.default([])
			})
	})

// removes context & id
export const chatTriggerUiMessageModel = z.discriminatedUnion('event', [
	chatTriggerUserMessageModel,
	cancelMessageModel,
	textMessageStartedModel.omit({ id: true }),
	textMessageContentModel.omit({ id: true }),
	textMessageEndModel.omit({ id: true }),
	runStartedModel.omit({ id: true }),
	runCompletedModel.omit({ id: true }),
	stepStartedModel.omit({ id: true }),
	stepCompletedModel.omit({ id: true })
])

// Array of messages
export const uiMessagesModel = z.array(uiMessageModel)
