/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import * as z from 'zod'

// Base schemas for common properties
const baseMessageModel = z.object({
	id: z.string(),
	event: z.string(),
	sourceId: z.string().optional(),
	runId: z.string().optional(),
	parentId: z.string().optional()
})

// Context schemas
export const nodeContextModel = z.object({
	event: z.literal('node')
})

export const contextModel = z
	.object({
		'@selectedNode': nodeContextModel.optional()
	})
	.optional()

// Role enum
const roleModel = z.enum(['user', 'assistant'])

// Text message schemas
export const textMessageStartedModel = baseMessageModel.extend({
	event: z.literal('text_message_started'),
	data: z.object({
		role: roleModel,
		context: contextModel.default({})
	})
})

export const textMessageContentModel = baseMessageModel.extend({
	event: z.literal('text_message_content'),
	sourceId: z.string(),
	data: z.object({
		delta: z.string()
	})
})

export const textMessageEndModel = baseMessageModel.extend({
	event: z.literal('text_message_end'),
	sourceId: z.string(),
	data: z.object({})
})

// Run schemas
export const runStartedModel = baseMessageModel.extend({
	event: z.literal('run_started'),
	data: z.object({})
})

export const runCompletedModel = baseMessageModel.extend({
	event: z.literal('run_completed'),
	sourceId: z.string(),
	data: z.object({})
})

// Step schemas
export const stepStartedModel = baseMessageModel.extend({
	event: z.literal('step_started'),
	runId: z.string(),
	data: z.object({
		title: z.string()
	})
})

export const stepCompletedModel = baseMessageModel.extend({
	event: z.literal('step_completed'),
	sourceId: z.string(),
	runId: z.string(),
	data: z.object({
		title: z.string()
	})
})

// Meta message schemas
export const ackMessageModel = baseMessageModel.omit({ id: true }).extend({
	event: z.literal('ack'),
	get data() {
		return uiMessageModel
	}
})

export const errorMessageModel = baseMessageModel.omit({ id: true }).extend({
	event: z.literal('error'),
	data: z.object({
		error: z.any() // Can contain validation errors or other error info
	})
})

const uiMessages = [
	textMessageStartedModel,
	textMessageContentModel,
	textMessageEndModel,
	runStartedModel,
	runCompletedModel,
	stepStartedModel,
	stepCompletedModel
] as const

// Union of all message types
export const uiMessageModel = z.discriminatedUnion('event', uiMessages)
export const messageModel = z.discriminatedUnion('event', [
	...uiMessages,
	ackMessageModel,
	errorMessageModel
])

// same but without id
export const newMessageModel = z.discriminatedUnion('event', [
	textMessageStartedModel.omit({ id: true }),
	textMessageContentModel.omit({ id: true }),
	textMessageEndModel.omit({ id: true }),
	runStartedModel.omit({ id: true }),
	runCompletedModel.omit({ id: true }),
	stepStartedModel.omit({ id: true }),
	stepCompletedModel.omit({ id: true })
] as const)

// Array of messages
export const uiMessagesModel = z.array(uiMessageModel)
