/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import * as z from 'zod'
import { componentMetaModel, nodePortModel } from './common.js'
import { jsonSchemaTypeModel } from './schema.js'

const abstractComponentModel = z.strictObject({
	id: z.uuidv4(),
	resource: z.string(),
	meta: componentMetaModel,
	spec: z.strictObject({})
})

export const ioModel = z.record(
	z.string().nonempty('IO name is required'),
	z.strictObject({
		description: z.string().default(''),
		schema: z.union([jsonSchemaTypeModel, z.record(z.never(), z.never())])
	})
)

const flowOutputModel = z.record(
	ioModel.keyType,
	ioModel.valueType.extend({
		source: z.string().nullable().meta({
			description: 'The ID of the node that is being fed into this node'
		}),
		target: z
			.string()
			.nullable()
			.meta({ description: 'The output of the source node' })
	})
)

// Action models (without complex validations)
export const actionSpecModel = z.strictObject({
	source: z.string(),
	requirements: z.string().optional().default(''),
	checksum: z.string().optional().default(''),
	readme: z.string().optional().default(''),
	runtime: z.literal('python-3.13').default('python-3.13'),
	inputs: ioModel,
	outputs: ioModel
})

export const actionModel = abstractComponentModel.extend({
	resource: z.literal('action/v1'),
	spec: actionSpecModel
})

const positionModel = z.strictObject({
	x: z.number(),
	y: z.number()
})

const nodeLoopModel = z
	.object({
		enabled: z.boolean().default(false),
		type: z.enum(['parallel']).nullish()
	})
	.default({ enabled: false })
	.refine(d => (d.enabled ? d.type === 'parallel' : true), {
		error: 'Loop type must be parallel if enabled'
	})

// Flow models (without async validations)
const flowNodeValueModel = z.strictObject({
	component_id: z.uuidv4(),
	inputs: z.record(z.string(), nodePortModel),
	position: positionModel.default({ x: 0, y: 0 }),
	get spec() {
		return componentModel
	},
	loop: nodeLoopModel
})

export const resolvedFlowNodeModel = z.record(
	z.string(),
	flowNodeValueModel.extend({
		get spec() {
			return resolvedComponentModel
		}
	})
)

const flowSpecModel = z.strictObject({
	readme: z.string().optional().default(''),
	nodes: z.record(z.string(), flowNodeValueModel.omit({ spec: true })),
	outputs: flowOutputModel,
	inputs: ioModel,
	// store location of the two "built-in" input/output nodes that are only visible inside of the flow
	io_nodes: z
		.strictObject({
			input: positionModel.default({ x: 0, y: 0 }),
			output: positionModel.default({ x: 0, y: 0 })
		})
		.default({
			input: { x: 0, y: 0 },
			output: { x: 0, y: 0 }
		})
})

export const flowModel = abstractComponentModel.extend({
	resource: z.literal('flow/v1'),
	spec: flowSpecModel
})

export const resolvedFlowModel = flowModel.extend({
	spec: flowModel.shape.spec.extend({
		nodes: resolvedFlowNodeModel
	})
})

// Agent models (without handlebars validation)
const agentPromptModel = z.array(
	z.strictObject({
		type: z.literal('template'),
		enabled: z.boolean().default(true),
		value: z.string()
	})
)

export const agentMessagesModel = z.object({
	description: z.string().default('Optional messages for the conversation'),
	schema: z
		.object({
			type: z.literal('array'),
			items: z.object({
				type: z.literal('object'),
				properties: z
					.record(z.string(), jsonSchemaTypeModel)
					.optional()
					.default({
						role: { type: 'string', default: 'user' },
						content: { type: 'string', default: 'Message content' }
					}),
				required: z.array(z.string()).optional().default(['role', 'content'])
			})
		})
		.default({
			type: 'array',
			items: {
				type: 'object',
				properties: {
					role: { type: 'string', default: 'user' },
					content: { type: 'string', default: 'Message content' }
				},
				required: ['role', 'content']
			}
		})
})

// Create a schema that optionally allows 'messages' field + allows additional fields
const agentIOModel = z
	.object({
		messages: agentMessagesModel.optional()
	})
	.and(ioModel)

export const availableAgentModels = [
	// OpenAI
	'openai/gpt-5.4',
	'openai/gpt-5.4-mini',
	'openai/gpt-5.4-nano',
	'openai/gpt-5',
	'openai/gpt-5-mini',
	'openai/gpt-5-nano',
	'openai/gpt-oss-120b',
	'openai/gpt-oss-20b',
	'openai/o4-mini',
	// Anthropic (Bedrock)
	'anthropic/claude-sonnet-4-6',
	'anthropic/claude-opus-4-6',
	'anthropic/claude-haiku-4-5',
	// MiniMax
	'minimax/MiniMax-M2.7',
	'minimax/MiniMax-M2.7-highspeed',
	// Mistral
	'mistral-medium-latest',
	'magistral-medium-latest',
	'codestral-latest',
	// Gemini
	'gemini/gemini-2.5-pro',
	'gemini/gemini-2.5-flash',
	'gemini/gemini-2.5-flash-lite',
	'gemini/gemini-3-pro-preview',
	// Scaleway
	'qwen3.5-397b-a17b',
	'qwen3-235b-a22b-instruct-2507',
	'qwen3-coder-30b-a3b-instruct',
	'mistral-small-3.2-24b-instruct-2506',
	'devstral-2-123b-instruct-2512',
	'holo2-30b-a3b',
	'llama-3.3-70b-instruct',
	'llama-3.1-8b-instruct',
	'gemma-3-27b-it',
	// Groq
	'qwen/qwen3-32b',
	'moonshotai/kimi-k2-instruct-0905',
	'llama-3.3-70b-versatile',
	'meta-llama/llama-4-scout-17b-16e-instruct',
	// legacy — hidden from UI but kept for backward compat with saved agents
	// (gateway routes these to new models)
	'anthropic/claude-sonnet-4-5',
	'openai/gpt-4.1',
	'openai/gpt-4.1-mini',
	'openai/gpt-4.1-nano',
	'openai/gpt-5.1',
	'openai/o3-mini',
	'openai/gpt-4o',
	'mistral-medium-2508',
] as const

const legacyModels = new Set([
	'anthropic/claude-sonnet-4-5',
	'openai/gpt-4.1',
	'openai/gpt-4.1-mini',
	'openai/gpt-4.1-nano',
	'openai/gpt-5.1',
	'openai/o3-mini',
	'openai/gpt-4o',
	'mistral-medium-2508',
])

export const visibleAgentModels = availableAgentModels.filter(
	m => !legacyModels.has(m)
)

const agentSpecModel = z.strictObject({
	// backwards compatibility: coerce old models to gemma-3-27b-it
	model: z.enum(availableAgentModels).catch('gemma-3-27b-it'),
	readme: z.string().optional().default(''),
	prompts: z.strictObject({
		system: agentPromptModel,
		user: agentPromptModel
	}),
	settings: z.strictObject({
		temperature: z.number().min(0).max(1).nullish(),
		topP: z.number().min(0).max(1).nullish(),
		maxTokens: z
			.number()
			.min(0)
			.max(100 * 1024)
			.default(32768)
			.nullish()
	}),
	nodes: z.record(
		z.string(),
		z.strictObject({
			component_id: z.uuidv4(),
			// loop: nodeLoopModel,
			inputs: z.record(
				z.string(),
				nodePortModel.extend({
					source: z.literal('parent')
				})
			),
			order: z.number().min(0)
		})
	),
	// agents should always have a messages input and output
	inputs: agentIOModel,
	outputs: agentIOModel
})

const resolvedAgentSpecModel = agentSpecModel.extend({
	nodes: z.record(
		agentSpecModel.shape.nodes.keyType,
		agentSpecModel.shape.nodes.valueType.extend({
			get spec() {
				return resolvedComponentModel
			}
		})
	)
})

export const agentModel = abstractComponentModel.extend({
	resource: z.literal('agent/v1'),
	spec: agentSpecModel
})

export const resolvedAgentModel = agentModel.extend({
	spec: resolvedAgentSpecModel
})

// Union models
export const componentSpecModel = z.union([
	flowSpecModel,
	actionSpecModel,
	agentSpecModel
])

export const componentModel = z.discriminatedUnion('resource', [
	flowModel,
	actionModel,
	agentModel
])

export const createComponentModel = z.discriminatedUnion('resource', [
	flowModel.omit({ id: true }),
	actionModel.omit({ id: true }),
	agentModel.omit({ id: true })
])

export const componentResourceModel = z.enum(
	componentModel.options.map(o => o.shape.resource.value)
)

export const resolvedComponentModel = z.discriminatedUnion('resource', [
	resolvedFlowModel,
	actionModel,
	resolvedAgentModel
])
