/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import * as z from 'zod'
import { abstractResourceModel, metaModel } from './common.js'
import { componentModel, resolvedComponentModel } from './components.js'
import {
	modifierMappingModel,
	unresolvedModifierMappingModel
} from './modifiers.js'
import { projectVariableModel } from './projects.js'

// expects everything to be fully resolved
export const executionModel = abstractResourceModel.extend({
	resource: z.literal('execution/v1'),
	meta: metaModel
		.omit({ intention: true })
		.extend({ name: z.string().optional() }),
	spec: z.strictObject({
		component: resolvedComponentModel,
		payload: z.record(z.string(), z.unknown()),
		modifiers: z
			.union([modifierMappingModel, unresolvedModifierMappingModel])
			.default({}),
		environment: z.object({
			variables: z.array(projectVariableModel)
		})
	})
})

const executionEventEnum = z.enum(['running', 'completed', 'failed', 'data'])

export const executionEventModel = z.strictObject({
	event: executionEventEnum,
	path: z.array(z.string()),
	payload: z.record(z.string(), z.unknown()),
	output: z.record(z.string(), z.unknown()),
	delta: z
		.string()
		.optional()
		.describe(
			"only used with data and for top-level agents. will be a partial of a json object that'll need to be dirtily parsed by the consumer"
		),
	stdout: z.string().optional(),
	stderr: z.string().optional(),
	stacktrace: z.string().optional()
})

export const executionRecordMetaModel = z.object({
	component: z
		.object({
			resource: z
				.enum(componentModel.options.map(o => o.shape.resource.value))
				.optional(),
			name: z.string().optional()
		})
		.optional()
		.default({})
})

const stringifiedJSON = <T extends z.ZodType>(schema: T) =>
	z.string().pipe(
		z.preprocess((input, ctx) => {
			try {
				return JSON.parse(input) as z.infer<T>
			} catch (_) {
				ctx.issues.push({ code: 'custom', message: 'Invalid JSON', input })
				return z.NEVER
			}
		}, schema)
	)

export const executionGlobalStreamEventModel = z.strictObject({
	executionId: z.string(),
	parentId: z.string().optional(),
	event: executionEventEnum,
	data: stringifiedJSON(
		z.strictObject({
			payload: z.record(z.string(), z.unknown()).optional(),
			output: z.record(z.string(), z.unknown()).optional(),
			stdout: z.string().optional(),
			stderr: z.string().optional(),
			stacktrace: z.string().optional(),
			component: executionRecordMetaModel.shape.component.optional()
		})
	),
	author: z.string()
})

export const workerTokenPayloadModel = z.strictObject({
	executionId: z.string(),
	orgId: z.string()
})

export const executionStates = [
	'pending',
	'running',
	'completed',
	'failed'
] as const
export const executionSources = [
	'scheduled_invocation',
	'endpoint',
	'chat',
	'manual',
	'builder'
] as const
export const executionStateEnum = z.enum(executionStates)
export const executionSourceEnum = z.enum(executionSources)

export const executionRecordModel = z.object({
	id: z.uuidv4(),
	state: executionStateEnum,
	parentId: z.uuidv4().nullable(),
	meta: executionRecordMetaModel,
	payload: z.record(z.string(), z.unknown()).nullable(),
	output: z.record(z.string(), z.unknown()).nullable(),
	stdout: z.string().nullable(),
	stderr: z.string().nullable(),
	stacktrace: z.string().nullable(),
	createdAt: z.coerce.date().nullable(),
	finishedAt: z.coerce.date().nullable(),
	ownedBy: z.string(),
	projectId: z.uuidv4().nullable(),
	deployedProjectId: z.uuidv4().nullable(),
	source: executionSourceEnum.nullable(),
	get children() {
		return z.array(executionRecordModel)
	}
})

export const executionsResponseModel = z.array(executionRecordModel)
