/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import * as z from 'zod'
import { abstractResourceModel, metaModel } from './common.js'
import { resolvedComponentModel } from './components.js'
import { modifierMappingModel } from './modifiers.js'

// expects everything to be fully resolved
export const executionModel = abstractResourceModel.extend({
	resource: z.literal('execution/v1'),
	meta: metaModel
		.omit({ intention: true })
		.extend({ name: z.string().optional() }),
	spec: z.strictObject({
		component: resolvedComponentModel,
		payload: z.record(z.string(), z.unknown()),
		modifiers: modifierMappingModel.default({})
	})
})

export const executionEventModel = z.strictObject({
	event: z.enum(['running', 'completed', 'failed']),
	path: z.array(z.string()),
	payload: z.record(z.string(), z.unknown()),
	output: z.record(z.string(), z.unknown())
})
