/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import type * as z from 'zod'
import type {
	actionModel,
	agentModel,
	componentModel,
	flowModel,
	resolvedAgentModel,
	resolvedComponentModel,
	resolvedFlowModel
} from './components.js'
import type { projectModel, resolvedProjectModel } from './projects.js'

export const isFlow = (
	component:
		| z.infer<typeof componentModel>
		| z.infer<typeof resolvedComponentModel>
		| z.infer<typeof resolvedProjectModel>
): component is z.infer<typeof flowModel> | z.infer<typeof resolvedFlowModel> =>
	component.resource === 'flow/v1'

export const isAgent = (
	component:
		| z.infer<typeof componentModel>
		| z.infer<typeof resolvedComponentModel>
		| z.infer<typeof resolvedProjectModel>
): component is z.infer<typeof agentModel> | z.infer<typeof resolvedAgentModel> =>
	component.resource === 'agent/v1'

export const isAction = (
	component:
		| z.infer<typeof componentModel>
		| z.infer<typeof resolvedComponentModel>
		| z.infer<typeof resolvedProjectModel>
): component is z.infer<typeof actionModel> => component.resource === 'action/v1'

export const isProject = (
	component:
		| z.infer<typeof componentModel>
		| z.infer<typeof resolvedComponentModel>
		| z.infer<typeof projectModel>
		| z.infer<typeof resolvedProjectModel>
): component is z.infer<typeof projectModel> | z.infer<typeof resolvedProjectModel> =>
	component.resource === 'project/v1'
