/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import * as z from 'zod'
import { metaModel, nodePathModel } from './common.js'

// Auth models
// TODO: add a custom provider that allows users to provide their own client id/secret
export const authSpecModel = z.strictObject({
	provider: z.enum([
		'google',
		'notion'
		// 'github',
		// 'dropbox',
		// 'microsoft'
		// 'shopify'
	]),
	scopes: z.array(z.string()).describe('scopes to request from the provider'),
	identifier: z
		.string()
		.nullish()
		.default(null)
		.describe('human readable identifier, set on authorisation success'),
	refreshToken: z
		.object({
			iv: z.string(),
			tag: z.string(),
			ciphertext: z.string()
		})
		.nullish()
		.default(null)
		.describe('encrypted refresh token, set on authorisation success')
})

export const authModel = z.strictObject({
	id: z.uuidv4().optional(),
	resource: z.literal('oauth/v1'),
	meta: metaModel,
	spec: authSpecModel
})

// Modifier union models
export const modifierSpecModel = z.union([authSpecModel])
export const modifierModel = z.discriminatedUnion('resource', [authModel])

// Basic modifier mapping without async validation
export const modifierMappingModel = z.record(
	nodePathModel,
	z.array(
		z.strictObject({
			modifier_id: z.uuidv4(),
			spec: modifierModel
		})
	)
)

export const modifierResourceModel = z.enum(
	modifierModel.options.map(o => o.shape.resource.value)
)
