/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import * as z from 'zod'
import { metaModel, nodePathModel } from './common.js'

const baseAuthSpecModel = z.object({
	identifier: z
		.string()
		.nullish()
		.default(null)
		.describe('human readable identifier, set on authorisation success'),
	refreshToken: z
		.object({
			iv: z.string(),
			tag: z.string(),
			ciphertext: z.string()
		})
		.nullish()
		.default(null)
		.describe('encrypted refresh token, set on authorisation success')
})

export const providers = {
	google: {
		scopes: [
			'https://www.googleapis.com/auth/userinfo.email',
			'https://www.googleapis.com/auth/drive',
			'https://www.googleapis.com/auth/drive.file',
			'https://www.googleapis.com/auth/drive.readonly',
			'https://www.googleapis.com/auth/drive.metadata.readonly',
			'https://www.googleapis.com/auth/gmail.readonly',
			'https://www.googleapis.com/auth/gmail.send',
			'https://www.googleapis.com/auth/gmail.modify',
			'https://www.googleapis.com/auth/gmail.compose',
			'https://www.googleapis.com/auth/calendar',
			'https://www.googleapis.com/auth/calendar.readonly',
			'https://www.googleapis.com/auth/calendar.events',
			'https://www.googleapis.com/auth/contacts',
			'https://www.googleapis.com/auth/contacts.readonly',
			'https://www.googleapis.com/auth/spreadsheets',
			'https://www.googleapis.com/auth/spreadsheets.readonly',
			'https://www.googleapis.com/auth/documents',
			'https://www.googleapis.com/auth/documents.readonly',
			'https://www.googleapis.com/auth/photoslibrary',
			'https://www.googleapis.com/auth/photoslibrary.readonly'
		]
	},
	notion: {
		scopes: []
	},
	microsoft: {
		scopes: [
			'Calendars.Read',
			'Calendars.ReadWrite',
			'Contacts.Read',
			'Contacts.ReadWrite',
			'email',
			'Files.Read',
			'Files.ReadWrite',
			'Mail.Read',
			'Mail.Read.Shared',
			'Mail.ReadWrite',
			'Mail.ReadWrite.Shared'
		]
	}
} as const

const google = baseAuthSpecModel.extend({
	provider: z.literal('google'),
	scopes: z.array(z.literal(providers.google.scopes))
})

const notion = baseAuthSpecModel.extend({
	provider: z.literal('notion'),
	scopes: z.array(z.string()) // TODO: set to never
})

const microsoft = baseAuthSpecModel.extend({
	provider: z.literal('microsoft'),
	scopes: z.array(z.literal([...providers.microsoft.scopes, 'profile']))
})

// Auth models
// TODO: add a custom provider that allows users to provide their own client id/secret
export const authSpecModel = z.discriminatedUnion('provider', [
	google,
	notion,
	microsoft
])

export const authModel = z.object({
	id: z.uuidv4().optional(),
	resource: z.literal('oauth/v1'),
	meta: metaModel,
	spec: authSpecModel
})

// Storage
export const storageSpecModel = z.object({
	// TODO: private/public access, lifecycle rules etc
})
export const storageModel = z.object({
	id: z.uuidv4().optional(),
	resource: z.literal('storage/v1'),
	meta: metaModel,
	spec: storageSpecModel
})

// databases
export const sqlSpecModel = z.object({
	password: z
		.object({
			iv: z.string(),
			tag: z.string(),
			ciphertext: z.string()
		})
		.nullish() // empty on creation
		.default(null)
		.describe('encrypted password used to access the db')
})
export const sqlModel = z.object({
	id: z.uuidv4().optional(),
	resource: z.literal('sql/v1'),
	meta: metaModel,
	spec: sqlSpecModel
})

// Modifier union models
export const modifierSpecModel = z.union([
	authSpecModel,
	storageSpecModel,
	sqlSpecModel
])
export const modifierModel = z.discriminatedUnion('resource', [
	authModel,
	storageModel,
	sqlModel
])

// Basic modifier mapping without async validation
export const modifierMappingModel = z.record(
	nodePathModel,
	z.array(
		z.strictObject({
			modifier_id: z.uuidv4(),
			spec: modifierModel
		})
	)
)

export const unresolvedModifierMappingModel = z.record(
	nodePathModel,
	z.array(
		z.strictObject({
			modifier_id: z.uuidv4()
		})
	)
)

export const modifierResourceModel = z.enum(
	modifierModel.options.map(o => o.shape.resource.value)
)
