/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import * as z from 'zod'
import { resolvedAgentModel, resolvedFlowModel } from './components'
import { resolvedProjectModel } from './projects'

export const nodesModel = z.union([
	resolvedFlowModel.shape.spec.shape.nodes,
	resolvedAgentModel.shape.spec.shape.nodes,
	resolvedProjectModel.shape.spec.shape.nodes
])
