/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import * as z from 'zod'
import { metaModel, nodePathModel } from './common.js'
import { resolvedComponentModel } from './components.js'
import { modifierMappingModel } from './modifiers.js'

const projectNodeModel = z.strictObject({
	component_id: z.uuidv4(),
	order: z.number().default(0)
})

export const projectVariableModel = z.strictObject({
	key: z.string(),
	value: z.string(),
	secret: z.literal(false)
})

// Project models (without async validations)
export const projectSpecModel = z.strictObject({
	readme: z.string().optional().default(''),
	nodes: z.record(z.string(), projectNodeModel).default({}),
	modifiers: z
		.record(
			nodePathModel,
			z.array(
				z.strictObject({
					modifier_id: z.uuidv4()
				})
			)
		)
		.default({}),
	environment: z
		.object({
			variables: z.array(projectVariableModel)
		})
		.default({
			variables: []
		}),
	triggers: z
		.object({
			endpoints: z.object({
				enabled: z.boolean().default(false),
				nodes: z.record(
					z.string(),
					z.object({
						method: z.literal('POST'),
						payload_mapping: z.record(z.string(), z.string())
					})
				),
				ingress_tokens: z.array(z.uuidv4()).default([])
			}),
			chat: z
				.object({
					enabled: z.boolean().default(false)
				})
				.default({ enabled: false })
		})
		.default({
			endpoints: {
				enabled: false,
				nodes: {},
				ingress_tokens: []
			},
			chat: {
				enabled: false
			}
		})
})

export const resolvedProjectSpecModel = projectSpecModel.extend({
	nodes: z
		.record(
			z.string(),
			projectNodeModel.extend({
				spec: resolvedComponentModel
			})
		)
		.default({}),
	modifiers: modifierMappingModel.default({})
})

export const projectModel = z.strictObject({
	id: z.uuidv4().optional(),
	resource: z.literal('project/v1'),
	meta: metaModel,
	spec: projectSpecModel
})

export const resolvedProjectModel = projectModel.extend({
	spec: resolvedProjectSpecModel
})

// data that's returned from the /deployments endpoint
// it doesn't include the entire spec, but rather just a checksum of it
export const deployedProjectDataModel = z.strictObject({
	id: z.string(),
	active: z.boolean(),
	createdAt: z.coerce.date(),
	checksum: z.string()
})

export const generatedProjectMetaModel = z.strictObject({
	name: z.string().nonempty().describe('Human-friendly name of the project'),
	readme: z
		.string()
		.describe('A concise markdown-formatted readme describing the project')
})
