/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

/** Pure binding checks shared by API, worker and generated clients. */
export function promptBindingProblems(spec: any): string[] {
	const problems: string[] = []
	for (const role of ['system', 'user'])
		for (const p of spec.prompts?.[role] ?? []) {
			if (!p.enabled || p.type !== 'template') continue
			for (const match of p.value.matchAll(/inputs\.([\w]+)((?:\.[\w]+)*)/g)) {
				if (match[1] === 'document_text' && spec.settings?.documentInput)
					continue
				const input = spec.inputs?.[match[1]]
				if (!input) {
					problems.push(`${role}: undeclared input ${match[1]}`)
					continue
				}
				let schema = input.schema
				for (const part of match[2].split('.').filter(Boolean)) {
					if (
						schema?.type &&
						schema.type !== 'object' &&
						schema.type !== 'array'
					) {
						problems.push(`${role}: field access on primitive ${match[0]}`)
						break
					}
					if (
						schema?.properties &&
						!(part in schema.properties) &&
						schema.additionalProperties === false
					) {
						problems.push(`${role}: undeclared field ${match[0]}`)
						break
					}
					schema = schema?.properties?.[part]
				}
			}
		}
	return [...new Set(problems)]
}
