/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import * as z from 'zod'

export const contextModel = z
	.array(
		z.strictObject({
			id: z.uuidv4(),
			text: z.string()
		})
	)
	.default([])

export const userStoriesModel = z
	.array(
		z.strictObject({
			id: z.uuidv4(),
			text: z.string()
		})
	)
	.default([])

export const outcomesModel = z
	.array(
		z.strictObject({
			id: z.uuidv4(),
			text: z.string()
		})
	)
	.default([])

export const guidelinesModel = z
	.array(
		z.strictObject({
			id: z.uuidv4(),
			text: z.string()
		})
	)
	.default([])

export const dependenciesModel = z
	.array(
		z.strictObject({
			id: z.uuidv4(),
			name: z.string(),
			description: z.string(),
			type: z.enum(['variable', 'secret'])
		})
	)
	.default([])

export const boundariesModel = z
	.array(
		z.strictObject({
			id: z.uuidv4(),
			text: z.string()
		})
	)
	.default([])

export const safetyModel = z
	.array(
		z.strictObject({
			id: z.uuidv4(),
			text: z.string()
		})
	)
	.default([])

export const requirementsModel = z.strictObject({
	context: contextModel,
	userStories: userStoriesModel,
	outcomes: outcomesModel,
	guidelines: guidelinesModel,
	dependencies: dependenciesModel,
	boundaries: boundariesModel,
	safety: safetyModel
})
