/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import * as z from 'zod'

// String type with constraints
const stringTypeSchema = z.object({
	type: z.literal('string'),
	minLength: z.number().int().min(0).optional(),
	maxLength: z.number().int().min(0).optional(),
	pattern: z.string().optional(),
	format: z
		.enum([
			'date',
			'time',
			'date-time',
			'email',
			'hostname',
			'ipv4',
			'ipv6',
			'uri',
			'uuid'
		])
		.optional(),
	enum: z.array(z.string()).optional(),
	default: z.string().optional()
})

// Number type with constraints
const numberTypeSchema = z.object({
	type: z.literal('number'),
	minimum: z.number().optional(),
	maximum: z.number().optional(),
	exclusiveMinimum: z.number().optional(),
	exclusiveMaximum: z.number().optional(),
	multipleOf: z.number().positive().optional(),
	enum: z.array(z.number()).optional(),
	default: z.number().optional()
})

// Integer type with constraints
const integerTypeSchema = z.object({
	type: z.literal('integer'),
	minimum: z.number().int().optional(),
	maximum: z.number().int().optional(),
	exclusiveMinimum: z.number().int().optional(),
	exclusiveMaximum: z.number().int().optional(),
	multipleOf: z.number().int().positive().optional(),
	enum: z.array(z.number().int()).optional(),
	default: z.number().int().optional()
})

// Boolean type
const booleanTypeSchema = z.object({
	type: z.literal('boolean'),
	enum: z.array(z.boolean()).optional(),
	default: z.boolean().optional()
})

// Null type
const nullTypeSchema = z.object({
	type: z.literal('null'),
	default: z.null().optional()
})

// Object type with recursive properties
const objectTypeSchema = z.object({
	type: z.literal('object'),
	get properties() {
		return z.record(z.string(), jsonSchemaTypeModel).optional()
	},
	get additionalProperties() {
		return z.union([z.boolean(), jsonSchemaTypeModel]).optional()
	},
	required: z.array(z.string()).optional(),
	default: z.record(z.string(), z.unknown()).optional()
})

// Array type with recursive items
const arrayTypeSchema = z.object({
	type: z.literal('array'),
	get items() {
		return jsonSchemaTypeModel.optional()
	},
	minItems: z.number().int().min(0).optional(),
	maxItems: z.number().int().min(0).optional(),
	uniqueItems: z.boolean().optional(),
	default: z.array(z.unknown()).optional()
})

// Enum schema (for when type is not specified but enum is)
const enumOnlySchema = z.object({
	enum: z
		.array(z.union([z.string(), z.number(), z.boolean(), z.null()]))
		.min(1),
	default: z.union([z.string(), z.number(), z.boolean(), z.null()]).optional()
})

// Any type schema (empty object or object with only default)
const anyTypeSchema = z
	.object({
		default: z.unknown().optional()
	})
	.strict()

// Composition schemas (defined with lazy to handle recursion)
const anyOfSchema = z.object({
	anyOf: z.lazy(() => z.array(jsonSchemaTypeModel).min(1))
})

const oneOfSchema = z.object({
	oneOf: z.lazy(() => z.array(jsonSchemaTypeModel).min(1))
})

const allOfSchema = z.object({
	allOf: z.lazy(() => z.array(jsonSchemaTypeModel).min(1))
})

// Main recursive schema
export const jsonSchemaTypeModel: z.ZodType<unknown> = z.lazy(() =>
	z.union([
		stringTypeSchema,
		numberTypeSchema,
		integerTypeSchema,
		booleanTypeSchema,
		nullTypeSchema,
		objectTypeSchema,
		arrayTypeSchema,
		enumOnlySchema,
		anyOfSchema,
		oneOfSchema,
		allOfSchema,
		anyTypeSchema // Keep this last to only match truly empty schemas
	])
)

/**
 * Analyzes Python type strings to determine required typing imports
 */
export const getRequiredImports = (pythonTypes: string[]): string[] => {
	const allTypesStr = pythonTypes.join(' ')
	const imports = ['TypedDict'] // Always need TypedDict for action generation

	if (allTypesStr.includes('Optional[')) imports.push('Optional')
	if (allTypesStr.includes('List[')) imports.push('List')
	if (allTypesStr.includes('Dict[')) imports.push('Dict')
	if (allTypesStr.includes('Union[')) imports.push('Union')
	if (allTypesStr.includes('Literal[')) imports.push('Literal')
	if (allTypesStr.includes('Any')) imports.push('Any')

	return imports
}

/**the
 * Converts a JSON schema to Python type annotation syntax
 * This function reverses the logic in pythonParser.ts
 */
export const schemaToPython = (schema: unknown): string => {
	if (!schema || typeof schema !== 'object') {
		return 'Any'
	}

	const s = schema as Record<string, unknown>

	// Handle basic types
	if (s.type === 'string') {
		if (s.enum && Array.isArray(s.enum)) {
			// String enum -> Literal
			const values = s.enum.map(v => `"${v}"`).join(', ')
			return `Literal[${values}]`
		}
		return 'str'
	}

	if (s.type === 'integer') {
		if (s.enum && Array.isArray(s.enum)) {
			// Integer enum -> Literal
			const values = s.enum.join(', ')
			return `Literal[${values}]`
		}
		return 'int'
	}

	if (s.type === 'number') {
		if (s.enum && Array.isArray(s.enum)) {
			// Number enum -> Literal
			const values = s.enum.join(', ')
			return `Literal[${values}]`
		}
		return 'float'
	}

	if (s.type === 'boolean') {
		if (s.enum && Array.isArray(s.enum)) {
			// Boolean enum -> Literal
			const values = s.enum.join(', ')
			return `Literal[${values}]`
		}
		return 'bool'
	}

	if (s.type === 'null') {
		return 'None'
	}

	if (s.type === 'array') {
		if (s.items) {
			const itemType = schemaToPython(s.items)
			return `List[${itemType}]`
		}
		return 'List[Any]'
	}

	if (s.type === 'object') {
		if (s.properties && typeof s.properties === 'object') {
			// Convert to TypedDict
			const properties = s.properties as Record<string, unknown>
			const fields: string[] = []
			const required = Array.isArray(s.required) ? (s.required as string[]) : []

			for (const [key, value] of Object.entries(properties)) {
				const fieldType = schemaToPython(value)
				const isRequired = required.includes(key)

				if (isRequired) {
					fields.push(`    ${key}: ${fieldType}`)
				} else {
					fields.push(`    ${key}: Optional[${fieldType}]`)
				}
			}

			if (fields.length > 0) {
				return `TypedDict('ObjectType', {\n${fields.join(',\n')}\n})`
			}
		}

		if (s.additionalProperties) {
			if (typeof s.additionalProperties === 'boolean') {
				return s.additionalProperties ? 'Dict[str, Any]' : 'Dict[str, Never]'
			} else {
				const valueType = schemaToPython(s.additionalProperties)
				return `Dict[str, ${valueType}]`
			}
		}

		return 'Dict[str, Any]'
	}

	// Handle enum without type
	if (s.enum && Array.isArray(s.enum)) {
		const values = s.enum
			.map(v => {
				if (typeof v === 'string') return `"${v}"`
				if (v === null) return 'None'
				return String(v)
			})
			.join(', ')
		return `Literal[${values}]`
	}

	// Handle composition schemas
	if (s.anyOf && Array.isArray(s.anyOf)) {
		const types = s.anyOf.map(schemaToPython)

		// Check for Optional pattern (Union with None)
		const nonNullTypes = types.filter(t => t !== 'None')
		const hasNull = types.includes('None')

		if (hasNull && nonNullTypes.length === 1) {
			return `Optional[${nonNullTypes[0]}]`
		}

		return `Union[${types.join(', ')}]`
	}

	if (s.oneOf && Array.isArray(s.oneOf)) {
		const types = s.oneOf.map(schemaToPython)
		return `Union[${types.join(', ')}]`
	}

	if (s.allOf && Array.isArray(s.allOf)) {
		// allOf is complex - for simplicity, we'll use the first schema
		// In practice, this might need more sophisticated handling
		if (s.allOf.length > 0) {
			return schemaToPython(s.allOf[0])
		}
	}

	// Fallback for empty schema or unknown patterns
	return 'Any'
}

export const getSamplePayload = (
	schema: z.infer<typeof jsonSchemaTypeModel>,
	visited = new WeakSet<object>()
): unknown => {
	// Handle null/undefined or non-object schemas
	if (!schema || typeof schema !== 'object') return 'any'

	// Check for circular references
	if (visited.has(schema)) return 'circular-reference'
	visited.add(schema)

	const s = schema as Record<string, unknown>

	// Handle basic types
	if (s.type === 'string') {
		// Use enum value if available
		if (s.enum && Array.isArray(s.enum) && s.enum.length > 0) return s.enum[0]
		// Use default if available
		if (s.default !== undefined) return s.default
		// Return sample based on format
		if (s.format) {
			switch (s.format) {
				case 'email':
					return 'user@example.com'
				case 'date':
					return '2024-01-01'
				case 'date-time':
					return '2024-01-01T00:00:00Z'
				case 'time':
					return '00:00:00'
				case 'uuid':
					return '550e8400-e29b-41d4-a716-446655440000'
				case 'uri':
					return 'https://example.com'
				case 'hostname':
					return 'example.com'
				case 'ipv4':
					return '192.168.1.1'
				case 'ipv6':
					return '2001:0db8:85a3:0000:0000:8a2e:0370:7334'
				default:
					return 'string'
			}
		}
		return 'string'
	}

	if (s.type === 'number') {
		// Use enum value if available
		if (s.enum && Array.isArray(s.enum) && s.enum.length > 0) return s.enum[0]
		// Use default if available
		if (s.default !== undefined) return s.default
		// Generate sample within constraints
		if (typeof s.minimum === 'number') return s.minimum + 1
		if (typeof s.maximum === 'number') return s.maximum - 1
		return 123.45
	}

	if (s.type === 'integer') {
		// Use enum value if available
		if (s.enum && Array.isArray(s.enum) && s.enum.length > 0) return s.enum[0]
		// Use default if available
		if (s.default !== undefined) return s.default
		// Generate sample within constraints
		if (typeof s.minimum === 'number') return s.minimum + 1
		if (typeof s.maximum === 'number') return s.maximum - 1
		return 123
	}

	if (s.type === 'boolean') {
		// Use enum value if available
		if (s.enum && Array.isArray(s.enum) && s.enum.length > 0) return s.enum[0]
		// Use default if available
		if (s.default !== undefined) return s.default
		return true
	}

	if (s.type === 'null') return null

	if (s.type === 'array') {
		// Use default if available
		if (s.default !== undefined) return s.default
		// Generate array with one sample item
		if (s.items) return [getSamplePayload(s.items, visited)]
		return ['any']
	}

	if (s.type === 'object') {
		// Use default if available
		if (s.default !== undefined) return s.default

		const result: Record<string, unknown> = {}

		if (s.properties && typeof s.properties === 'object') {
			const properties = s.properties as Record<string, unknown>
			const required = Array.isArray(s.required) ? (s.required as string[]) : []

			// Add all required properties
			for (const key of required) {
				if (properties[key])
					result[key] = getSamplePayload(properties[key], visited)
			}

			// Optionally add some non-required properties for demonstration
			for (const [key, value] of Object.entries(properties)) {
				if (!required.includes(key) && Object.keys(result).length < 3) {
					// Add first few optional properties for sample
					result[key] = getSamplePayload(value, visited)
				}
			}
		}

		// If no properties defined but additionalProperties is allowed
		if (Object.keys(result).length === 0) {
			if (s.additionalProperties === true) return { sampleKey: 'any' }
			if (
				s.additionalProperties &&
				typeof s.additionalProperties === 'object'
			) {
				return { sampleKey: getSamplePayload(s.additionalProperties, visited) }
			}
		}

		return Object.keys(result).length > 0 ? result : {}
	}

	// Handle enum without type
	if (s.enum && Array.isArray(s.enum) && s.enum.length > 0) return s.enum[0]

	// Handle composition schemas
	if (s.anyOf && Array.isArray(s.anyOf) && s.anyOf.length > 0) {
		// Use first schema option for sample
		return getSamplePayload(s.anyOf[0], visited)
	}

	if (s.oneOf && Array.isArray(s.oneOf) && s.oneOf.length > 0) {
		// Use first schema option for sample
		return getSamplePayload(s.oneOf[0], visited)
	}

	if (s.allOf && Array.isArray(s.allOf) && s.allOf.length > 0) {
		// Merge all schemas (simplified - just use first for sample)
		return getSamplePayload(s.allOf[0], visited)
	}

	// Empty schema or unknown pattern
	return 'any'
}
