/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import * as z from 'zod'
import { componentModel } from './components.js'

const baseModel = z.strictObject({
	event: z.string(),
	data: z.unknown()
})

const componentUpdated = baseModel.extend({
	event: z.literal('component:updated'),
	data: {
		component: componentModel
	}
})

export const socketEventModel = z.discriminatedUnion('event', [
	componentUpdated
])
