/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import * as z from 'zod'
import { componentModel } from './components.js'
import { deployedProjectDataModel, resolvedProjectModel } from './projects.js'
import { requirementsModel } from './requirements.js'

const baseModel = z.strictObject({
	event: z.string(),
	// arbitrary ID to ensure the author of updates don't receive an "echo" when they do stuff
	author: z.string().optional(),
	data: z.record(z.string(), z.unknown())
})

const connected = baseModel.extend({
	event: z.literal('connected'),
	data: z.strictObject({
		id: z.string()
	})
})

const componentUpdated = baseModel.extend({
	event: z.literal('component:updated'),
	data: z.strictObject({
		component: componentModel
	})
})

const componentRequirementsUpdated = baseModel.extend({
	event: z.literal('component:requirements:updated'),
	data: z.strictObject({
		component_id: z.string(),
		requirements: requirementsModel
	})
})

const projectUpdated = baseModel.extend({
	event: z.literal('project:updated'),
	data: z.strictObject({
		project: resolvedProjectModel
	})
})

export const projectDeployed = baseModel.extend({
	event: z.literal('project:deployed'),
	data: z.strictObject({
		deployment: deployedProjectDataModel
	})
})

export const socketEventModel = z.discriminatedUnion('event', [
	componentUpdated,
	connected,
	componentRequirementsUpdated,
	projectUpdated,
	projectDeployed
])
