/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import { z } from 'zod'

const prompt = z.object({
	initialPrompt: z.string()
})

export const telemetryModel = z.union([prompt])
