/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import * as z from 'zod'

export const storageTokenPayloadModel = z.object({
	modifierId: z.string(),
	scope: z.enum(['r', 'w', 'rw']),
	path: z
		.string()
		.optional()
		.describe('restricts the token to a specific path prefix')
})
