/**
 * This file is automatically generated from nexus/api/src/models/schemas/
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * Run nexus/sync.sh to update these files
 */

import * as z from 'zod'

// Primitive types
const primitiveTypeSchema = z.object({
	type: z.enum(['string', 'number', 'boolean', 'null'])
})

// Object type with recursive properties
const objectTypeSchema = z.object({
	type: z.literal('object'),
	get properties() {
		return z.record(z.string(), jsonSchemaTypeModel).optional()
	},
	get additionalProperties() {
		return jsonSchemaTypeModel.optional()
	}
})

// Array type with recursive items
const arrayTypeSchema = z.object({
	type: z.literal('array'),
	get items() {
		return jsonSchemaTypeModel.optional()
	}
})

// Main recursive schema
export const jsonSchemaTypeModel = z.union([
	primitiveTypeSchema,
	objectTypeSchema,
	arrayTypeSchema
])

export const jsonSchemaTypeToPython = (
	typeModel: z.infer<typeof jsonSchemaTypeModel> | Record<string, never>
): string => {
	// Handle empty object (no type information)
	if (Object.keys(typeModel).length === 0) {
		return 'Any'
	}

	const type = typeModel as z.infer<typeof jsonSchemaTypeModel>

	switch (type.type) {
		case 'string':
			return 'str'
		case 'number':
			return 'int'
		case 'boolean':
			return 'bool'
		case 'null':
			return 'None'
		case 'array':
			if (type.items) {
				const itemType = jsonSchemaTypeToPython(type.items)
				return `List[${itemType}]`
			}
			return 'List'
		case 'object':
			if (type.additionalProperties) {
				const valueType = jsonSchemaTypeToPython(type.additionalProperties)
				return `Dict[str, ${valueType}]`
			}
			if (type.properties) {
				// For objects with specific properties, we'd need TypedDict
				// but for simplicity, we'll return Dict[str, Any]
				return 'Dict[str, Any]'
			}
			return 'Dict'
		default:
			return 'Any'
	}
}
