apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: {{ .Release.Name }}
      port: {{ .Values.port }}
    enableWebsockets: true
    timeoutPolicy:
      response: 600s
      idle: 600s
  virtualhost:
    fqdn: {{ .Values.httpproxy.fqdn }}
    tls:
      secretName: {{ .Values.httpproxy.tls.secretName }}
