apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  postgres_url: {{ .Values.postgres_url | b64enc | quote }}