postgres_url: ENC[AES256_GCM,data:IYPSapT2mdyqCC168SDUE+xqVBqtOuqM/EwQzcFmLFxxEpR4t2CONITJv5juE8KaMfjLvSbOuGvDrfzCVOLqbC135ILHC05SkCSs9NGfmAa+btKe8+IIXUGc++LdpvVMj2yjtvqrw+LQJ3NKX/7Du1XdEg==,iv:GsjUwd3aCwY5C9SfViefGd8QlX56aNuzEjb0YxBf67w=,tag:GGahnBdFA9QqELQ4CiOCxA==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/triformcloud/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2025-05-28T17:08:04Z"
          enc: CiQAnBVPiGYV2MANEvZqn1/VMvK7UZWkZlM/ksmnLI5AFb96I0YSSQA5FVhkaFAKyFcReK2zZ1jyB5EWiSZtawxNv2k9aeBuurNGZJsluEIXrAswlpZUKtpo4G+XIut/zc6pz3FlY19LVSPVrZAWedk=
    lastmodified: "2025-05-28T17:09:51Z"
    mac: ENC[AES256_GCM,data:KYufCEt+vmaZ+eknijD6lZccN6g5m9EanSL75obHXPcDMQkdvxShM/+LVbUKgVmFUx5g02EQzsScBbAHKyVmBxHId81OfPCzIo9ejUYnD/RMmfTl/41unCvs15nZil49vrVYTuOFAEqaOEe1qpsyrubDtmuECS5knq9QB2FFTUs=,iv:TErrwJp8eIf9cZIMBvKftYE8zeAyRF9+uBgVidsRDyw=,tag:VXDf2aWgWQhTuQ4Ed04whA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
