/**
import type { UUID as Uuid } from "crypto" 
export type { Uuid } 

 * Types generated from repo agent-worker/schema.json
 * based on the following commit:
 *
 * Repo: agent-worker
 * Branch: HEAD -> tri-231/refactoring, origin/tri-231/refactoring
 * Commit Hash: 6c20c0e0b179daf10906dd8a652084dcd865d551
 * Date: Mon Jan 27 18:09:38 2025 +0200
 * */

/* eslint-disable */
import type { UUID as Uuid } from 'crypto'
export type { Uuid }

/**
import type { UUID as Uuid } from "crypto" 
export type { Uuid } 

 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Source = 'parent' | Uuid

export interface Node {
	component_id: Uuid
	component_version?: number | null
	inputs?: Source[]
	spec: Action | Agent
	[k: string]: unknown
}
export interface Action {
	resource: 'action/v1'
	meta: Meta
	spec: {
		source: string
		readme: string
		deps: string
		checksum?: string
		streaming: boolean
		[k: string]: unknown
	}
	[k: string]: unknown
}
export interface Meta {
	name: string
	id: Uuid
	version: number
	[k: string]: unknown
}
export interface Agent {
	resource: 'agent/v1'
	meta: Meta
	spec: {
		readme: string
		nodes: {
			[k: string]: Node
		}
		outputs: Uuid[]
		[k: string]: unknown
	}
	[k: string]: unknown
}
