/**
 * Types generated from repo agent-worker/schema.json on Fri Jan 10 14:17:52 UTC 2025
 * based on the following commit:
 *
 * Repo: agent-worker
 * Branch: HEAD -> tri-231/refactoring, origin/tri-231/refactoring
 * Commit Hash: 8b86216601c9fc3f87927b66bee039b8733c9964
 * Date: Fri Jan 10 14:13:04 2025 +0100
 * */

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ResourceV1 = {
	[k: string]: unknown
} & {
	resource: string
	api_version: 'v1'
	id: string
	key: string
	inputs?: string[]
	spec: unknown
}
export type StatementV1 = ResourceV1 | SequenceStatementV1 | ParallelStatementV1

export interface InvocationV1 {
	resource: 'invocation'
	api_version: 'v1'
	input: unknown
	spec: ResourceV1
}
export interface ActionSpecV1 {
	name: string
	version: number
	action: ActionStatementV1
}
export interface ActionStatementV1 {
	source: string
	readme: string
	deps?: string
	layer?: string
	streaming: boolean
}
export interface AgentSpecV1 {
	name: string
	version: number
	agent: StatementV1
}
export interface SequenceStatementV1 {
	sequence: StatementV1[]
}
export interface ParallelStatementV1 {
	parallel: StatementV1[]
}
