/**
 * Types generated from repo agent-worker/schema.json
 * based on the following commit:
 *
 * Repo: agent-worker
 * Branch: HEAD -> master, origin/master, origin/HEAD
 * Commit Hash: b690b50c1372b3dea9d714070d2331777cc2837d
 * Date: Thu Nov 28 15:54:35 2024 +0100
 * */

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ResourceV1 = {
  [k: string]: unknown;
} & {
  resource: string;
  api_version: "v1";
  id: string;
  key: string;
  inputs?: string[];
  spec: unknown;
};
export type StatementV1 = ResourceV1 | SequenceStatementV1 | ParallelStatementV1;

export interface InvocationV1 {
  resource: "invocation";
  api_version: "v1";
  input: unknown;
  spec: ResourceV1;
}
export interface ActionSpecV1 {
  name: string;
  version: number;
  action: ActionStatementV1;
}
export interface ActionStatementV1 {
  source: string;
  readme: string;
  deps?: string;
  layer?: string;
  streaming: boolean;
}
export interface AgentSpecV1 {
  name: string;
  version: number;
  agent: StatementV1;
}
export interface SequenceStatementV1 {
  sequence: StatementV1[];
}
export interface ParallelStatementV1 {
  parallel: StatementV1[];
}
